spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://coursedb.cq8siaiawpql.us-east-1.rds.amazonaws.com:3306/courses_db
    username: admin
    password: password1
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server-env-1.tvtpbphqfw.us-east-1.elasticbeanstalk.com/eureka
      #defaultZone: http://eurekaserver-env-1.dydpn5kspa.us-east-1.elasticbeanstalk.com/eureka
server:
  error:
    include-stacktrace: on_trace_param
